version: '3.9'
services:
  metabase:
    image: metabase/metabase:latest
    volumes: 
    - /dev/urandom:/dev/random:ro
    environment: 
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase123
      MB_DB_HOST: postgres
      TZ: "Asia/Manila"
      JAVA_TIMEZONE: "Asia/Manila"
    restart: unless-stopped
    networks: 
      - backend
      - npm_dmz
    depends_on: 
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: metabase123
      TZ: "Asia/Manila"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    networks: 
      - backend

volumes:
   db-data: {}
networks: 
   npm_dmz:
      external: true
   backend:
      driver: bridge:
